---
title: "00 Seed Germination Retesting List"
author: "Katie Heineman"
date: "6/4/2019"
output: html_document
---

# How to create a procedure for retesting, while still gaining data for publication?

# Assumptions

+ Every quarter we can run 30 tests (120 test per year)
+ Each year we have around 20 rare seed collections

# Data Import
```{r set up}
library(data.table)
library(httr)
library(RCurl)
library(rjson)
library(jsonlite)

# Reading in Caspio Token
source("Tokens/caspioSource.R")
# Reading in caspio GET command (don't know if this works for things > 1000)
source("caspioFunctions.R")

# Read in Datasets
germTest <- caspio_get_table("Germination",login1)
seedAcc <- caspio_get_view("Seed_Accession_All_Info",login1)
germLog <- fread("Data/GerminationLog_2019-Jun-04_2151.csv")

# Select Columns from desired datasets
seedAccLim <- seedAcc[Deaccessioned==0,.(SeedAccessionNumber,ScientificName,CNPSRank,LocalityName,DateSeedCollected,MaternalLinesSampled,DateFrozen)]
```

# Make Table of Status for Each Accession

```{r status}

## Finding inital counts of germinants
# Summarize Germination Test Initial Counts for those with initial values in the initital count columns (new database format)
germTestInitLong <- melt(germTest[!is.na(Rep1Init)],
                     id.vars=c("PK_ID","SeedAccessionNumber"),
                     measure.vars = names(germTest)[grepl("Init",names(germTest))]
                     ,variable.name="Rep"
                    , value.name="InitialCount",na.rm=T) # this code is not performing correctly
# Remove "_Init" from rep column
germTestInitLong[,Rep:=gsub('Init', '', Rep)]

# Summarize Germination Test Initial Counts & # of Germinants from test in the old format
germTestInitOld <- germTest[is.na(Rep1Init) & !is.na(NumberSeedsPulled),.(PK_ID,SeedAccessionNumber, InitialCount=NumberSeedsPulled,NumGerminantsOld=NumGerminants)]
germTestInitOld[,Rep:="Old"]

# Bind two initial tests together
germTestLong <- rbind(germTestInitLong,germTestInitOld,fill=T)

## Reshaping germination Log
# melt germLog so that we have one observation for each rep
germLogMelt <- melt(germLog, id.vars = c("GermLogID","GermTestID","DateChange", names(germLog)[15:18]), measure.vars = names(germLog)[5:14], variable.name="Rep",value.name="measurementCount",na.rm=T)
# Remove "_Count" from rep column
germLogMelt[,Rep:=gsub('_.*', '', Rep)]
germLogMelt[,measurementDate:=as.Date(DateChange,format="%m/%d/%Y")]

# Merge together log and germ tests
germMerge <- merge(germTestLong, germLogMelt, by.x=c("PK_ID","Rep"), by.y=c("GermTestID","Rep"), all.x=T)

# Count the Germinants Per Rep
germCountsbyRep = germMerge[,.(InitialCount=(InitialCount[1]), MaxCount = max(as.numeric(measurementCount),na.rm=T),NumGerminantsOld=NumGerminantsOld[1]), by=c("SeedAccessionNumber","PK_ID", "Rep")]
# Summarizing Germinants by Test (taking into account old tests)
germCountsbyTest  = germCountsbyRep[,.(SeedsTested=sum(InitialCount), Germinants = ifelse(is.na(NumGerminantsOld), sum(MaxCount),as.numeric(NumGerminantsOld))), by=c("SeedAccessionNumber","PK_ID")]
# Calculate Percent Germination
germCountsbyTest[,GermPercent:=round(sum(Germinants)/sum(SeedsTested)*100)]

# Make a Table of the Test Types Completed
germinationSummary <- germCountsbyTest[,.(Baseline=ifelse(grepl("Initial",toString(TestType)),"Yes","No"), 
                                 
                                       BaselineStatus=toString(Baseline[TestType=="Initial"])),by="SeedAccessionNumber"]

```